### ISSUE TITLE
Crash On Attempt to Treat or Analyze

### ISSUE THREAD

**Issue by StrangeWill** [t-richards/chemo#24]
```
Application: Chemo.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFDF65FFD85 (00007FFDF6550000) with exit code 80131506.
```

Super useful, investigating on my end...

**Comment by StrangeWill** [comment]
That's cool -- Windows update fixed it, I may set up a new VM to investigate further.

**Comment by t-richards** [comment]
e3c9cbb033b09f8cfcde8771c5de4f87dc12cbd3 changes builds to debug mode; that way all users should be able to easily see a full stack trace for issues like these.

**Comment by t-richards** [comment]
@StrangeWill any idea which Windows 10 version/build you were running prior to doing updates?

**Comment by StrangeWill** [comment]
No, but I can deploy a new VM with the same install media and re-try, I'll do that.

**Comment by t-richards** [comment]
Please use the latest build from AppVeyor in your testing, if you don't mind 😁 

https://ci.appveyor.com/project/t-richards/chemo/build/artifacts

**Comment by StrangeWill** [comment]
I'm getting this error now:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'Windows.ApplicationModel.PackageSignatureKind Windows.ApplicationModel.Package.get_SignatureKind()'.
   at Chemo.Treatment.Apps.RemoveStoreApps.ShouldPerformTreatment()
   at Chemo.frmMain.<>c__DisplayClass16_0.<BtnAnalyze_Click>b__0() in C:\projects\chemo\src\Chemo\frmMain.cs:line 262
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Chemo.frmMain.<BtnAnalyze_Click>d__16.MoveNext() in C:\projects\chemo\src\Chemo\frmMain.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Chemo
    Assembly Version: 0.2.35.0
    Win32 Version: 0.2.35.0
    CodeBase: file:///C:/Users/william/Downloads/Dev_Resources/Chemo.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Windows.Management
    Assembly Version: 255.255.255.255
    Win32 Version: 
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.Management.winmd
----------------------------------------
Windows.Foundation
    Assembly Version: 255.255.255.255
    Win32 Version: 
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Windows.ApplicationModel
    Assembly Version: 255.255.255.255
    Win32 Version: 
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
Windows.System
    Assembly Version: 255.255.255.255
    Win32 Version: 
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.System.winmd
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by t-richards** [comment]
The docs tell me that the `Package.SignatureKind` property was introduced in Windows 10  Anniversary Edition v10.0.14393.0 https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.signaturekind

Support for that build ended on April 10, 2018 (https://en.wikipedia.org/wiki/Windows_10_version_history). Maybe update your vanilla install image? 😜 

We may need to specify build 14393 as a minimum requirement for Chemo. Otherwise I'm not sure how to prevent it from uninstalling "system" store packages.

**Comment by StrangeWill** [comment]
Yeah, this is old install media, I guess setting a minimum version of 14393 would work fine (not sure how I could lock to that version to verify that's the safest "minimum" version though).

**Comment by t-richards** [comment]
Hmm... Actually, I think I have an idea about how I can avoid using the `SignatureKind` property. I'll make some changes today and then I'll ask you to give it another shot 😄

**Comment by t-richards** [comment]
@StrangeWill Please try `v0.2.36.0` and see if this fixes your issue. Download: https://ci.appveyor.com/project/t-richards/chemo/builds/29293135/artifacts

It should be sufficient to just download the `.exe` - I don't think you need the `Dev_Resources.zip` unless you just really want to have the `.pdb` file around 😁

**Comment by StrangeWill** [comment]
Ouch, got a hard crash again now.

```
Faulting application name: Chemo (1).exe, version: 0.2.36.0, time stamp: 0x5de6f185
Faulting module name: clr.dll, version: 4.6.1586.0, time stamp: 0x575a1507
Exception code: 0xc0000005
Fault offset: 0x00000000001c0045
Faulting process id: 0x950
Faulting application start time: 0x01d5fa3ab2bd5691
Faulting application path: C:\Users\william\Desktop\Chemo (1).exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: ad31fdb4-36c7-4683-b135-763a26815687
Faulting package full name: 
Faulting package-relative application ID: 
```

I deployed an old image to upgrade for some other purpose so I figured I'd poke at this, honestly it's probably a non-issue since 1803 is even out of support at this point. A "hey you're on an unsupported version" error would be nice but eh.
